---
log:
  level: DEBUG

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: DNSnet
    watch: true

certificatesResolvers:
  leresolver:
    acme:
      email: joe@abcd.com
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
